# Generated by Django 4.0.5 on 2022-07-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('CEO', 'Presidente'), ('DIR', 'Diretor'), ('GER', 'Gerente'), ('COORD', 'Coordenador'), ('SUPER', 'Supervisor'), ('LID', 'Líder'), ('SR', 'Sênior'), ('PL', 'Pleno'), ('JR', 'Júnior'), ('TR', 'Trainee')], max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
    ]
